[yhchat]                                       # 与云湖连接的ws服务设置
userId = "1234567"                             # 云湖用户的ID
token = "00000000-0000-4000-0000-000000000000" # 云湖用户的Token
deviceid = "web-device-id"                     # 云湖用户的设备ID
heartbeat_interval = 30                        # 心跳间隔（按秒计）
retry_wait = 5                                 # 重连等待时间（按秒计）

[maibot]           # 连接麦麦的ws服务设置
host = "localhost" # 麦麦在.env文件中设置的主机地址，即HOST字段
port = 8000        # 麦麦在.env文件中设置的端口，即PORT字段

[chat] # 黑白名单功能
group_list_type = "whitelist"   # 群组名单类型，可选为：whitelist, blacklist
group_list = ["123456789"]      # 群组名单
                                # 当group_list_type为whitelist时，只有群组名单中的群组可以聊天
                                # 当group_list_type为blacklist时，群组名单中的任何群组无法聊天

private_list_type = "whitelist" # 私聊名单类型，可选为：whitelist, blacklist
private_list = ["1234567"]      # 私聊名单
                                # 当private_list_type为whitelist时，只有私聊名单中的用户可以聊天
                                # 当private_list_type为blacklist时，私聊名单中的任何用户无法聊天

ban_user_id = ["1234567"]       # 全局禁止名单（全局禁止名单中的用户无法进行任何聊天）
ban_bot = false                 # 是否屏蔽云湖官方机器人

