# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/yhchat.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'proto/yhchat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/yhchat.proto\x12\x05proto\x1a\x19google/protobuf/any.proto\"\x17\n\x07\x43ontent\x12\x0c\n\x04text\x18\x01 \x01(\t\"p\n\x03Msg\x12!\n\x06header\x18\x01 \x01(\x0b\x32\x11.proto.Msg.Header\x12\"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x1a\"\n\x06Header\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"\x8e\x02\n\x0bPushMessage\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12)\n\x06sender\x18\x02 \x01(\x0b\x32\x19.proto.PushMessage.Sender\x12\x0e\n\x06\x63hatId\x18\x04 \x01(\t\x12!\n\x08\x63hatType\x18\x05 \x01(\x0e\x32\x0f.proto.ChatType\x12\x1f\n\x07\x63ontent\x18\x06 \x01(\x0b\x32\x0e.proto.Content\x12\x13\n\x0b\x63ontentType\x18\x07 \x01(\x03\x12\x0c\n\x04time\x18\x08 \x01(\x03\x1aI\n\x06Sender\x12\n\n\x02id\x18\x01 \x01(\t\x12!\n\x08\x63hatType\x18\x02 \x01(\x0e\x32\x0f.proto.ChatType\x12\x10\n\x08nickname\x18\x03 \x01(\t\"\x8a\x01\n\x0bSendMessage\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\x0e\n\x06\x63hatId\x18\x03 \x01(\t\x12!\n\x08\x63hatType\x18\x04 \x01(\x0e\x32\x0f.proto.ChatType\x12\x1f\n\x07\x63ontent\x18\x05 \x01(\x0b\x32\x0e.proto.Content\x12\x13\n\x0b\x63ontentType\x18\x06 \x01(\x03*5\n\x08\x43hatType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04USER\x10\x01\x12\t\n\x05GROUP\x10\x02\x12\x07\n\x03\x42OT\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.yhchat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATTYPE']._serialized_start=609
  _globals['_CHATTYPE']._serialized_end=662
  _globals['_CONTENT']._serialized_start=56
  _globals['_CONTENT']._serialized_end=79
  _globals['_MSG']._serialized_start=81
  _globals['_MSG']._serialized_end=193
  _globals['_MSG_HEADER']._serialized_start=159
  _globals['_MSG_HEADER']._serialized_end=193
  _globals['_PUSHMESSAGE']._serialized_start=196
  _globals['_PUSHMESSAGE']._serialized_end=466
  _globals['_PUSHMESSAGE_SENDER']._serialized_start=393
  _globals['_PUSHMESSAGE_SENDER']._serialized_end=466
  _globals['_SENDMESSAGE']._serialized_start=469
  _globals['_SENDMESSAGE']._serialized_end=607
# @@protoc_insertion_point(module_scope)
